version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neo_tax_take_home
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build: .
    image: "neo-tax/take-home"
    command: npm run db:migration:deploy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/neo_tax_take_home?schema=public
    depends_on:
      db:
        condition: service_healthy

  seed_db:
    build: .
    image: "neo-tax/take-home"
    command: npm run db:seed
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/neo_tax_take_home?schema=public
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - seed_db

  app:
    image: "neo-tax/take-home"
    container_name: "take-home"
    depends_on:
      - migration
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: true # required for nodemon reloading
      DATABASE_URL: postgresql://postgres:postgres@db:5432/neo_tax_take_home?schema=public
      PORT: 8080
      HOST: 0.0.0.0

volumes:
  pgdata:
